62 exceptions
InternetEnemies/combatcritters-sharp pull request #63
Opened 2024-11-08 20:37 UTC by idafum

2024-11-25 21:20 UTC, VanJackal requested changes
in general, errors shouldn't be handled in wrapper unless we are adding additional context. The GeneralExceptionHandler is removing the context from the exceptions that are thrown.

The better way (which I think you already started) is to have a single parent exception (CombatCrittersException) that is extended by any of the exceptions being thrown in the wrapper.

for stuff like ArgumentException, it shouldn't be wrapped, and probably shouldn't be caught in the ui either. If that is being thrown it implies the caller sent an invalid input, which it shouldn't do.

2024-11-25 21:20 UTC, VanJackal commented on CombatCrittersSharp/exception/GeneralExceptionHandler.cs
> +            );
wrapping every exception like this will prevent the catching of more specific errors in the ui

2024-11-25 21:20 UTC, VanJackal commented on CombatCrittersSharp/managers/PacksManager.cs
> +                return new List<UserPack>();
unreachable code, this applies to any time that something iis called after HandleException is called

2024-11-25 21:20 UTC, VanJackal commented on CombatCrittersSharp/exception/GeneralExceptionHandler.cs
> +            }
instead of this the additional details could be added to the constructors of the exceptions. for the excetions that aren't custom they probably shouldnt be wrapped, or should be wrapped with new custom exceptions at their throw point

2024-11-25 21:20 UTC, VanJackal commented on CombatCrittersSharp/managers/PacksManager.cs
> +            }
don't catch exceptions thrown in the try block

2024-11-25 21:20 UTC, VanJackal commented on CombatCrittersSharp/rest/Rest.cs
>          };
It may be worth adding a catch for some of the regular exceptions here and throwing a WrapperNetworkException, as well as changing adding a throw for auth exception for whenever the status code is 403 or 401

2024-11-26 06:57 UTC, idafum commented
I'm kinda just getting the gist regarding exceptions. I'll fix these

2024-11-27 23:33 UTC, VanJackal approved these changes

2024-11-28 03:54 UTC, merged